server.port=8080

# =========================
# MongoDB
# =========================

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}


# =========================
# Redis
# =========================

spring.cache.type=redis

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}

spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=6000ms


# =========================
# Mail (Gmail SMTP)
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=cxat.app@gmail.com
spring.mail.password=afnaanlbwxhhuxhk

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# =========================
# IMPORTANT (Fix Render Mail Timeout)
# =========================

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000