mongodb+srv://cxatapp_db_user:cwLj4DyPklxz3EhU@cluster0.c3pkg67.mongodb.net/cxatapp?retryWrites=true&w=majority
# springboot ke  port ko 8080 set kar diya hai, aur Redis ke liye host aur port configure kar diye hain.
server.port=8080

# redis components ke liye configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379